baseURL = "https://goldthorpescouts.org.uk/"
languageCode = "en-gb"
title = "Goldthorpe Scouts"
theme = "alpha-church"

enableEmoji = true
customCSS = ["", ""]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level theme.
#Use the weight= to specify the order of menu items, and the parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "about"
    weight = 2

  [[menu.main]]
    name = "About Us"
    parent = "About"
    url = "/about"
    weight = 1
 
  [[menu.main]]
    name = "Our Sections"
    parent = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    parent = "About"
    url = "/leaders"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Paramaters for the whole site
[params]
  title = "Goldthorpe Scouts"
  subtitle = "Adventure!"
  author = "Goldthorpe Scouts"

  bible_popups = true

  [params.map]
    # For Open Street Map widgets
    latitude = "53.53637"
    longitude = "-1.30250"
    zoom = "17"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact_thanks"
    # formspree_email=""

  #Paramaters for the home/landing page
  [params.landing]

    [params.landing.banner]
      image = "img/banner.jpg"

      [[params.landing.banner.button]]
        url = "/contact"
        text = "Get in touch"
        type = "special"

        [[params.landing.banner.button]]
        url = "/about"
        text = "Find out more"

    #Details for the box below the banner
    [params.landing.services]
      title = "Everyday Adventure"
      text = "We meet at [Goldthorpe Scouts HQ, Lockwood Road, Goldthorpe](https://www.openstreetmap.org/node/705292616)."
      map_location = "Lockwood Road, Goldthorpe"

    [params.landing.feature_icons]
      #These feature icons look best if there's an even number of them.
      enable = true

      #Accent is a colour defined in the CSS file. Choose between 1 and 5
      [[params.landing.feature_icons.tile]]
        icon = "fa-tree"
        icon_pack = "fas"
        accent = "1"
        title = "Beavers"
        text = "Growing people who serve our community."

      [[params.landing.feature_icons.tile]]
        icon = "fa-user-friends"
        icon_pack = "fas"
        accent = "2"
        title = "Cubs"
        text = "Meeting together to hear."

      [[params.landing.feature_icons.tile]]
        icon = "fa-fire"
        icon_pack = "fas"
        accent = "5"
        title = "Scouts"
        text = "Speaking encouragement to one-another."

      [[params.landing.feature_icons.tile]]
        icon = "fa-user-friends"
        icon_pack = "fas"
        accent = "3"
        title = "Join Us"
        text = "Apply to join the fun!"

    [params.landing.feature_images]
      #These feature images look best if there's an even number of them.
      enable = true

      [[params.landing.feature_images.tile]]
        image = "img/freely-10057.jpg"
        title = "Childrens' Ministry"
        text = "A church for the family."
        url = "/kids"
        button_text = "Learn more"

      [[params.landing.feature_images.tile]]
        image = "img/freely-26905.jpg"
        title = "Midweek Ministries"
        text = "Want more during the week?"
        url = "#"
        button_text="Join a group today!"

    [params.landing.CTA]
      heading = "Get in touch!"
      message = "We'd love to hear from you."

    [params.footer]
      copyright = "[CC0 (public domain)](http://creativecommons.org/publicdomain/zero/1.0/)"

    [[params.links]]
      service = "Twitter"
      icon = "fa-twitter"
      icon_pack = "fab"
      link = "//twitter.com/goldthorpescout"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/goldthorpescouts"


    [[params.links]]
      service = "Full RSS Feed"
      icon = "fa-rss"
      icon_pack = "fas"
      link = "/index.xml"
