baseURL = "https://scouts.scottguymer.co.uk/"
customCSS = ["", ""]
enableEmoji = true
enableGitInfo = true
googleAnalytics = "UA-120779958-1"
languageCode = "en-gb"
theme = "alpha-church"
title = "Goldthorpe Scouts"
[[menu.main]]
name = "Parents"
url = "/parents"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Leaders"
parent = "Our Sections"
url = "/leaders"
weight = 4
[[menu.main]]
name = "Scouts"
parent = "Our Sections"
url = "/scouts"
weight = 3
[[menu.main]]
name = "Cubs"
parent = "Our Sections"
url = "/cubs"
weight = 2
[[menu.main]]
name = "Beavers"
parent = "Our Sections"
url = "/beavers"
weight = 1
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 6
[[menu.main]]
name = "Blog"
url = "/posts"
weight = 5
[[menu.main]]
name = "Our Sections"
weight = 3
[[menu.main]]
name = "About"
url = "/about"
weight = 2
[params]
author = "Goldthorpe Scouts"
formspree_email = "contact@goldthorpescouts.org.uk"
subtitle = "Everyday adventure for young people with an award winning Scout Group"
title = "6th Barnsley (Goldthorpe)"
[params.contact]
service = "formspree"
[params.footer]
copyright = "[&copy; Goldthorpe Scouts 2018](http://creativecommons.org/publicdomain/zero/1.0/)"
[params.landing.CTA]
heading = "Get in touch!"
message = "We'd love to hear from you."
[params.landing.banner]
image = "img/banner.jpg"
[[params.landing.banner.button]]
text = "Get in touch"
type = "special"
url = "/contact"
[[params.landing.banner.button]]
text = "Find out more"
url = "/about"
[params.landing.feature]
image = "/img/sunset_scouts.jpg"
[params.landing.feature_icons]
enable = true
[[params.landing.feature_icons.tile]]
img = "/img/logos/beavers-logo-blue-png.png"
text = "Our youngest section from 6 to 8 1/2"
title = "Beavers"
url = "/beavers"
[[params.landing.feature_icons.tile]]
img = "/img/logos/cubs-logo-green-png.png"
text = "Our growing young people from 8 to 10 1/2"
title = "Cubs"
url = "/cubs"
[[params.landing.feature_icons.tile]]
img = "/img/logos/scouts-logo-green-png.png"
text = "Our oldest adventureres from 10 1/2 to 14"
title = "Scouts"
url = "/scouts"
[[params.landing.feature_icons.tile]]
img = "/img/group_badge.png"
text = "Join the fun!"
title = "Join Us"
url = "/join"
[params.landing.feature_images]
enable = true
[[params.landing.feature_images.tile]]
button_text = "Learn more"
image = "img/pioneering.jpg"
text = "Want to learn more?"
title = "About Us"
url = "/about"
[[params.landing.feature_images.tile]]
button_text = "Join our group today!"
image = "img/den2.jpg"
text = "Want your child to do more during the week?"
title = "Join in the adventure"
url = "/join"
[params.landing.services]
map_location = "Lockwood Road, Goldthorpe"
text = "Welcome to Goldthorpe Scouts! We are a local Scout group run by volunteers for young people aged from 6 to 14. We are passionate about scouting and want to make sure that every child gets the opportunity for adventure. <br /><br /> Our group is split into sections for different age groups. You can read more about them below."
title = "Everyday Adventure"
[[params.links]]
icon = "fa-twitter"
icon_pack = "fab"
link = "//twitter.com/goldthorpescout"
service = "Twitter"
[[params.links]]
icon = "fa-facebook"
icon_pack = "fab"
link = "//facebook.com/goldthorpescouts"
service = "Facebook"
[[params.links]]
icon = "fa-rss"
icon_pack = "fas"
link = "/index.xml"
service = "Full RSS Feed"
[taxonomies]
series = "series"
tag = "tags"
